.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ICKLE 1 "December 11, 2001"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ickle \- a GTK+ ICQ 2000 capable icq client
.SH SYNOPSIS
.B ickle
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B ickle
commands.
.PP
\fBickle\fP is a GTK+ ICQ client. Using the ICQ2000 protocol it is
capable of using new icq features like sending sms messages to mobile
phones.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.BI \-b "\| dir\^"
Use this parameter to set the
.B ickle
base directory to
.IR dir .
It defaults to
.B $HOME/.ickle.
If you use this option the configuration files are searched in
.IR dir
instead
.SH SEE ALSO
.BR ickle_applet (1)
.br
.SH AUTHOR
This manual page was written by Dominik 'Aeneas' Schnitzer <dominik@schnitzer.at>,
for the Debian GNU/Linux system (but may be used by others).
