.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ICKLE_APPLET 1 "December 11, 2001"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ickle_applet \- a GTK+ ICQ 2000 capable icq client with GNOME panel
applet support.
.SH SYNOPSIS
.B ickle_applet
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B ickle_applet
commands.
.PP
\fBickle_applet\fP is a GTK+ ICQ client. Using the ICQ2000 protocol it
is capable of using new icq features like sending sms messages to
mobile phones. In contrast to \fBickle(1)\fP \fBickle_applet\fP has
GNOME panel support. Right click on your GNOME panel and add the Ickle
ICQ applet from the Network section to your panel.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.BI \-b "\| dir\^"
Use this parameter to set the
.B ickle_applet
base directory to
.IR dir .
It defaults to
.B $HOME/.ickle.
If you use this option the configuration files are searched in
.IR dir 
instead
.SH SEE ALSO
.BR ickle (1)
.br
.SH AUTHOR
This manual page was written by Dominik 'Aeneas' Schnitzer <dominik@schnitzer.at>,
for the Debian GNU/Linux system (but may be used by others).
.br
Modified by Barnaby Gray <barnaby@beedesign.co.uk>
